### ISSUE TITLE
Flatpak package outdated

### ISSUE THREAD

**Issue by skipperTux** [flathub/chat.delta.desktop#100]
Hello.
When opening the Flatpak app it shows a Device Messages saying "This build is over 120 days old - There might be a new version available." The [GitHub deltachat-desktop repository](https://github.com/deltachat/deltachat-desktop) is at version 1.34.0, Flatpak is at version 1.32.1. However in the Desktop repository at Linux - Flatpak it says "The primary distribution-independed way to install is to use the flatpak build."
Is this not true anymore? Is the Flatpak package deprecated?

**Comment by muelli** [comment]
https://github.com/flathub/chat.delta.desktop/pull/97 tries to update the app, but the technologies chosen make it more difficult than normal applications. Feel free to assist in pushing it over the finish line.

**Comment by muelli** [comment]
yeah, could well be that others have stumbled upon similar issues.
I invite you to try and build it yourself :)
The [instructions](https://github.com/flathub/chat.delta.desktop/blob/master/README.md)  should get you going. If they don't, then it's a bug in the documentation! So please try and see how far you get with the instructions provided.
