### ISSUE TITLE
Deltachat won't start

### ISSUE THREAD

**Issue by Lucas-Sichardt** [flathub/chat.delta.desktop#102]
Hello,

flatpak seems to be very nice but I’m having trouble with my first installation. I have downloaded Delta Chat and it will not start with the following error:

bwrap: Can’t mount devpts on /newroot/dev/pts: Invalid argument
[2 preload-host-spawn-strategy] Failed to let stub process know of exit: Ungültiger Dateideskriptor (errno 9)

What could this mean or what can I do about this?

**Comment by muelli** [comment]
hm.

sounds like something is wonky with your flatpak installation.

What version do you have installed? How have you installed it? How have you installed delta chat? And does installing any other app work? And what are you executing there that causes the problem you have?

I recommend running programs with LC_ALL=C so that you don't get localised output.

**Comment by muelli** [comment]
strange.
can you follow https://flatpak.org/setup/ and install and run any app from flathub?



> I have Flatpak version 1.12.6 and I have installed it via the ppa (flatpak stable).

I'm surprised. I would have expected flatpak to be in any serious distribution by now. Is there a reason why you chose the PPA over your distribution's repository? There's 1.12.7 now, too. But also 1.14.1. Can you work with the version of your distribution?

I could only find [this](https://github.com/containers/bubblewrap/issues/13) from more than six years ago.

Anyway, unless you manage to run any other app, this is a problem with flatpak in your distribution. I suggest you file a bug with your distribution about it.

**Comment by Lucas-Sichardt** [comment]
I've tried it: Chessx can be installed and run via Flatpak.
So it seems that Flatpak itself can run on my system - even if the
system is runing on an old version of LinuxMint which is the reason for
installing Flatpak via PPA - and the reason for using Flatpak at all to
run Deltachat - I guess under a newer version of my distribution
Deltachat would just run as .deb package...

-- 

Diese Nachricht wurde gesendet mit Evolution unter Linux Mint Xfce.Am Freitag, den 20.01.2023, 12:33 -0800 schrieb muelli:

**Comment by nbenitez** [comment]
> I could only find [this](https://github.com/containers/bubblewrap/issues/13) from more than six years ago.

Apparently that bug was fixed in Bubblewrap 0.1.0, but maybe this may be another bubblewrap issue fixed recently.. Lucas maybe you need an updated Bubblewrap, maybe installed via PPA too..

**Comment by Lucas-Sichardt** [comment]
Thanks for your advice.
I have installed Bubblewrap now via ppa. But it seems that there was no
Bullbewrap installed at all before.
Either way: Even after installing it, Deltachat won't start and it's
the same error message.
-- 

Diese Nachricht wurde gesendet mit Evolution unter Linux Mint Xfce.Am Freitag, den 20.01.2023, 14:57 -0800 schrieb Nelson Benitez Leon:

**Comment by Simon-Laux** [comment]
Does this issue still exist?

**Comment by Simon-Laux** [comment]
please reopen or comment if it is still an issue
