### ISSUE TITLE
LAST COMMIT / MOBIAN

### ISSUE THREAD

**Issue by CHRISHERBET** [flathub/chat.delta.desktop#106]
ID: chat.delta.desktop
       Ref: app/chat.delta.desktop/aarch64/stable
      Arch: aarch64
    Branch: stable
Collection: org.flathub.Stable
  Download: 138,1 Mo
 Installed: 347,0 Mo
   Runtime: org.freedesktop.Platform/aarch64/22.08
       Sdk: org.freedesktop.Sdk/aarch64/22.08

    Commit: 8dc9021ed54dcc035f6fd1429404c58a097e7e535d3f961f5dd31c78e073dde1

with this commit and mobian the text of the messages is white
when writing a new message the text is white too.

with the previous commit (Commit: 907235648f3bc8fe7117c185c7b58061db4c11d823cd16e48cead4240e6403cf) there was not this problem

**Comment by CHRISHERBET** [comment]
The Flathub repository is https://flathub.org/repo/flathub.flatpakrepo
(activated by executing : flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo)

flatpak remote-info --log flathub chat.delta.desktop 

        ID: chat.delta.desktop
       Ref: app/chat.delta.desktop/aarch64/stable
      Arch: aarch64
    Branch: stable
Collection: org.flathub.Stable
  Download: 135,1 Mo
 Installed: 338,0 Mo
   Runtime: org.freedesktop.Platform/aarch64/22.08
       Sdk: org.freedesktop.Sdk/aarch64/22.08

    Commit: 24c5ed07f13cc57ea6951025ebb5b25965572cf31e341068e3658053140ebfc4
    Parent: 8dc9021ed54dcc035f6fd1429404c58a097e7e535d3f961f5dd31c78e073dde1
   Subject: bump to v1.36.1 (57d0aa1c)
      Date: 2023-04-11 06:31:06 +0000
   History: 

    Commit: 8dc9021ed54dcc035f6fd1429404c58a097e7e535d3f961f5dd31c78e073dde1
   Subject: bump runtime to 22.08 (b927c414)
      Date: 2023-03-28 18:45:32 +0000

    Commit: 907235648f3bc8fe7117c185c7b58061db4c11d823cd16e48cead4240e6403cf
   Subject: regenerate npm sources (7b8333fc)
      Date: 2023-02-19 07:40:56 +0000

    Commit: 6378cbbe8e5ab06fe9fae2999c6a25b43d899c37581fe89092bf5bd1f8acd985
   Subject: regenerate npm sources (7b8333fc)
      Date: 2023-02-19 07:40:56 +0000

    Commit: e8a26f881eb396b656b1d77234a31f08577a2e01bd0ca127efc25db6b1018b36
   Subject: update to 1.34.2 (fc24b161)
      Date: 2023-01-19 15:17:46 +0000

    Commit: 3d4d9f49829ca29c8603d3ed341fafeea3b4a7ab0843652095efdef3457d4cc9
   Subject: update to v1.34.1 (0c122c14)
      Date: 2022-12-24 19:49:43 +0000

    Commit: ef39593c5db1fbe1801692fcd8af25547e1ce2d3792b7beb3a2ee9860e288dab
   Subject: remove unused file (b8d601b3)
      Date: 2022-08-19 14:22:44 +0000

    Commit: f09bb6dc2d02f3f4ee6a39254139d4ec80d48af48bc8bdaa57e387c3ff4bf36c
   Subject: create tempdir like gasinvein recommended fix version number (dec82114)
      Date: 2022-08-19 12:05:29 +0000

    Commit: 7246766cb319a07cccba402a43971fcd36e33e5b797fa9e0673b6022e58dc405
   Subject: fix commit hash (5e973841)
      Date: 2022-06-07 18:50:13 +0000

    Commit: df7000c8867949a37a40da67fe2adceb083ced1fe1ee2b0113ab1c4f56a13323
   Subject: Simplify and clean up npm build (4f7655d0)
      Date: 2022-04-26 18:25:01 +0000

**Comment by Simon-Laux** [comment]
can you send a screenshot so it's clear what you mean?

**Comment by CHRISHERBET** [comment]
![Capture d’écran du Commit:907235648f3bc8fe7117c185c7b58061db4c11d823cd16e48cead4240e6403cf](https://user-images.githubusercontent.com/130004484/232214232-6d31391a-8994-47cf-8280-b5455ee08b9b.png)
![Capture d’écran du Commit: 8dc9021ed54dcc035f6fd1429404c58a097e7e535d3f961f5dd31c78e073dde1](https://user-images.githubusercontent.com/130004484/232214718-f1b8a63f-a7c5-4363-8990-31021734ac1e.png)

**Comment by Simon-Laux** [comment]
how does it look in the dark theme of deltachat?

**Comment by CHRISHERBET** [comment]
same for the dark theme

![Capture d’écran du 2023-04-15 15-08-02](https://user-images.githubusercontent.com/130004484/232225849-ee4fe150-5cd6-4d8c-8727-69267c01ca82.png)

**Comment by Simon-Laux** [comment]
does this issue still exist?

**Comment by CHRISHERBET** [comment]
This problem was solved without me doing anything.
