### ISSUE TITLE
Wrong picture on Flathub

### ISSUE THREAD

**Issue by maymage** [flathub/chat.delta.desktop#112]
Hi all, 

the picture of Delta Chat on [Flathub](https://flathub.org/apps/chat.delta.desktop) is misleading, as it does not show the menu bar. 

See https://github.com/deltachat/deltachat-desktop/issues/3225

**Comment by maymage** [comment]
Menu bar is this thing here

![image](https://github.com/flathub/chat.delta.desktop/assets/36572014/c1068eea-8279-48db-8704-a4fe40cff222)

**Comment by muelli** [comment]
I'm confused.
What do you get and what have you expected instead?

**Comment by Simon-Laux** [comment]
@muelli it's a macOS screenshot, also it's outdated, I agree that it needs to be replaced soon.
