### ISSUE TITLE
source in deltachat-core-rust.yaml appear to be outdated

### ISSUE THREAD

**Issue by horas13** [flathub/chat.delta.desktop#121]
Most of the modules referenced in deltachat-core-rust.yaml seem outdated, namely
* sqlcipher
* tcl
* sccache
* deltachat itself

I do not fully know the build process, but I guess they should be updated, no?

**Comment by muelli** [comment]
yeah, updating those makes sense. I wonder why we need to build, e.g. sqlcipher, ourselves and why it doesn't come through upstream's Cargo.lock.
Ideally, we'd have x-checker-data to make the bot check for updates and propose them.
