### ISSUE TITLE
What is the purpose of `--env=XDG_CURRENT_DESKTOP=Unity`

### ISSUE THREAD

**Issue by Mikaela** [flathub/chat.delta.desktop#128]
The flatpak lies to the app that Unity is the currently used desktop environment and there is no comment on why.

I have experienced this behaviour causing crashes in other apps previously.

**Comment by muelli** [comment]
where do you find that definition?

**Comment by Mikaela** [comment]
Wrong repository, sorry, I messed up tabs in hurry in the morning, will fix soonish.
