### ISSUE TITLE
Use appstream and .desktop from dc-desktop repo

### ISSUE THREAD

**Issue by flub** [flathub/chat.delta.desktop#17]
The appstream file is now in the dc-desktop repo.  We should merge any changes made here which are relevant and build from that one.

**Comment by flub** [comment]
Include .desktop file which is now also there.

**Comment by muelli** [comment]
yay. it'd be awesome to not having to maintain those files.

**Comment by flub** [comment]
Looking at the .desktop, I don't think it makes sense for that one since `Exec=/app/bin/run.sh` which is specific to flatpak really.  So perhaps that shouldn't have been put in the deltachat-desktop repo?

**Comment by muelli** [comment]
AFAIU electron is capable of generating .desktop files.
And I think we're making use of that, so this issue is obsolete.
We don't have the desktop file any more, so it must come from upstream :)
