### ISSUE TITLE
Delta Chat fails to load

### ISSUE THREAD

**Issue by marmulak** [flathub/chat.delta.desktop#29]
Installed the latest Delta Chat from flathub using Fedora 31 x86_64, found that running the app normally produces the following error:

>[3:0225/213249.770849:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/delta/chrome-sandbox is owned by root and has mode 4755.
>/app/bin/run.sh: line 2:     3 Trace/breakpoint trap   (core dumped) /app/delta/deltachat-desktop

The app is able to run with the `--no-sandbox`, which I achieved by editing run.sh to enable passing arguments. (adding `"$@"` after /app/delta/deltachat-desktop).

Hope this helps.

**Comment by marmulak** [comment]
chat.delta.desktop version is given as v1.0.0

**Comment by muelli** [comment]
Thanks. I pushed the fix.
https://github.com/flathub/chat.delta.desktop/commit/115fa6deec5cf6f4b38e88c05130d0bca3b97aca
