### ISSUE TITLE
Generated manifests are using inline data instead of urls

### ISSUE THREAD

**Issue by TingPing** [flathub/chat.delta.desktop#31]
This is quite awful, the repo is massive, and it makes it all impossible to audit.

The sources should be URLs from a trusted third party, not kept in tree.

**Comment by muelli** [comment]
welcome to the work of webapps bundled with Electron apps.

**Comment by TingPing** [comment]
Well according to @refi64 its impossible to use npm securely...

So I guess we are all doomed.

**Comment by refi64** [comment]
Some more background (already mentioned on IRC but for any other readers): the sources are downloaded separately, but the metadata from npm's APIs need to be saved here, because their return value isn't stable and thus can't be used as downloaded URLs.
