### ISSUE TITLE
v1.12.0 is out, still don't know how to trigger flathub builds

### ISSUE THREAD

**Issue by Jikstra** [flathub/chat.delta.desktop#43]

**Comment by muelli** [comment]
if you'd make proper github releases, i.e. through their web form, then I'd get a notification. Currently, it looks like this: 
![image](https://user-images.githubusercontent.com/322807/89210440-613c4b80-d5c0-11ea-831c-b5f58b17fcab.png)


Which parts of the instructions in the README are you struggling with? I'd expect some rough edges, but without knowing what can be filed off, it's poking in the dark.

**Comment by Jikstra** [comment]
I think it's less a problem of the README or anything and more being completely disconnected to the flathub eco system. We are not making any proper gihtub releases anymore, as we push all artefacts to download.delta.chat/desktop/ . But if it helps you, we can do it again :)

**Comment by Jikstra** [comment]
I have to admit that i'm not too much interested in maintaining the flatpaks myself, so i'm also not too much interested in diving into how to create/update flatpaks. Still quite a lot of people seem to use the delta.chat flatpak, so i think it's worth it to keep it up to date. The question is, do you have time & motivation to maintain this? If so I would love to find a release workflow that fits us all :)

**Comment by muelli** [comment]
> I have to admit that i'm not too much interested in maintaining the flatpaks myself

Fair enough, but to me, the title that you've chosen for this bug doesn't suggest that you're ignorant about the Flathub releases but that the instructions are not clearly communicated.

> The question is, do you have time & motivation to maintain this?

It's a weird question to me, because from where I am sitting, I have pushed updates the day I have been made aware of the release. There may indeed have been a delay here and there, but I fail to see how you can ask this question if you're not even following the work that is being performed here.

To answer your question: Well. I wouldn't mind more people doing the actual work, but I guess that is normal.

**Comment by muelli** [comment]
> Still quite a lot of people seem to use the delta.chat flatpak

It's good that it finally seems to be noticed that distributing apps as flatpak through flathub has major advantages. I'd go as far as saying that it's the only sane distribution of the app, that you offer. Arguably, for a security relevant tool, the update mechanism is the most crucial functionality. You could roll your own, but you better don't. And flatpak / flathub has a strong story for handling updates. Of course, you could start arguing about post-compromise security, but still, I think it's trivially better than the appimage or whatever else you have.

**Comment by Jikstra** [comment]
> It's a weird question to me, because from where I am sitting, I have pushed updates the day I have been made aware of the release. There may indeed have been a delay here and there, but I fail to see how you can ask this question if you're not even following the work that is being performed here.

Okay I'm sorry, then I communicated this quite sloppy and wrongly. First of, I'm very thankful for you maintaining this and didn't want to be ignorant about the work & effort you put into this, even if it's now quite clear to me that this is what I communicated with the title I chose. I didn't remember that you need published github releases to get a notification about a new release, and somehow had in my mind this old detail of needing to create an issue to trigger a build. That's why I chose this sloppy title, not to disrespect you or anything like this. Sorry for the miscommunication.

**Comment by muelli** [comment]
the update to 1.12.0 is being attempted here: https://github.com/flathub/chat.delta.desktop/pull/44

**Comment by groovenectar** [comment]
I see, it looks to be complicated getting it packaged for Flathub like a whole other platform to figure out

**Comment by Simon-Laux** [comment]
If you want to help https://github.com/flathub/chat.delta.desktop/pull/68

**Comment by groovenectar** [comment]
Thanks for letting me know, I'd not been aware of these layers before!
