### ISSUE TITLE
remove unused stuff that makes the flatpak bigger than it should be

### ISSUE THREAD

**Issue by Simon-Laux** [flathub/chat.delta.desktop#63]
file path | size in bytes | comment
-- | -- | --
delta/resources/app/node_modules/deltachat-node/prebuilds | _19100000 | if we build it for that flatpack we probably don’t need it, if its still used we should change that - its still used, issue tracked in #62 
delta/resources/app/node_modules/deltachat-node/deltachat-core-rust | __2800000 | [T] don’t need sources
node/ | _87400000 | [T] → Not needed
bin/sccache | _14900000 | [T] build artifact - not used
 |  | 
Total | 124200000 | 

_[T] means tested: deleting it and app still worked afterwards_

potential space savings: **124MB** (of the installed/extracted size download size impact will be smaller)

**Comment by muelli** [comment]
yeah, the sccache should be removed. If the other items can also be deleted, all the better.
Files to be removed can be given with the `cleanup` key in the manifest.

**Comment by muelli** [comment]
in app/node_modules/mapbox-gl/dist some files are clocking in with big weights.
mapbox-gl-dev.js or mapbox-gl-unminified.js.map.
Do you know whether they are used?
There is also a "src" directory with 5.6MB. I guess that either "dist" or "src" is being used, so there's some potential to shave things off.

blueprintjs is the second largest directory with 8.2MB.
