### ISSUE TITLE
what is sccache useful for?

### ISSUE THREAD

**Issue by Simon-Laux** [flathub/chat.delta.desktop#69]
I get that it speeds up subsequent builds, but I do not know if it also speeds up first builds.
Also I can not find the place where the cache is persisted, and without somewhat persistent cache it doesn't work. unless sccache also speeds up initial builds.

**Comment by Simon-Laux** [comment]
So it actually is persisted between runs?

**Comment by muelli** [comment]
yeah, should be, when you run flatpak-builder with the `--ccache` option
