### ISSUE TITLE
Repo access for deltachat team

### ISSUE THREAD

**Issue by flub** [flathub/chat.delta.desktop#7]
Hi, the deltachat team would like to use the flatpak format as preferred linux destkop distribution media and figure out how to streamline releases etc.  It'd probably be helpful if they could make changes to this repo for releases etc.  I assume it's possible to delegate to e.g. https://github.com/orgs/deltachat/people ?

**Comment by muelli** [comment]
right now, @ralphtheninja has access. Having an approval from that account would be very good.

**Comment by ralphtheninja** [comment]
@muelli I approve of this :)

**Comment by muelli** [comment]
can we have a list of accounts that should be able to write to this repository?
then I would ask, e.g. @barthalion to add those to the repository.

**Comment by ralphtheninja** [comment]
To start with:

* @flub 
* @jikstra
* @Simon-Laux

**Comment by TingPing** [comment]
@ralphtheninja 	Invited.

**Comment by muelli** [comment]
thanks!
