### ISSUE TITLE
The tray icon is blurred

### ISSUE THREAD

**Issue by darhma** [flathub/chat.delta.desktop#78]
The tray icon of flatpak version 1.26.0 is blurred compared to the same version installed via .deb

Here I've talked about it on the forum including the image: https://support.delta.chat/t/help-testing-the-upcoming-1-25-x-release/1926/31

**Comment by Simon-Laux** [comment]
is this still the case for you? I could not reproduce it on gnome, which desktop environment are you using?

**Comment by darhma** [comment]
Yes, the problem is still there and when I receive new messages the icon is "broken" (I'm now replying from mobile and have no way to take a screenshot). I use kde/plasma on debian sid/unstable (I think it's version 5.24.something of kde/plasma)

**Comment by darhma** [comment]
However tomorrow I'll see better by doing the updates on desktop (anyway I'm using version 1.28) and maybe I'll do some additional screenshots

**Comment by darhma** [comment]
Version 1.28.2 (git: flathub) on debian sid/unstable with kde/plasma 5.24.4 is the broken icon on the right (it's broken when I've unread messages) on the left is the icon of the appimage version
![Screenshot_20220428_065126](https://user-images.githubusercontent.com/11388812/165678972-f7acc610-0040-4680-b87e-5babd3b6ea39.png)
![Screenshot_20220428_064619](https://user-images.githubusercontent.com/11388812/165679019-fa3f330e-e67c-479c-b83c-acd46ac5cae9.png)

**Comment by darhma** [comment]
OK if no one else has experienced the problem I think the report can be closed, in the meantime I have changed distro and the problem has not occurred again
